name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-and-test:
    name: Test openpai-runtime on python-${{ matrix.python}}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7]
        os: [ubuntu-16.04, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kubernetes pyyaml requests jinja2 pystache pylint responses
    - name: Lint openpai-runtime
      run: |
        pylint --rcfile=.pylintrc src
    - name: Test openpai-runtime
      run: |
        cd test
        python -m unittest discover .

